apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-cni-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-cni-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: istio-cni
    namespace: {{ .Release.Namespace }}